"""Root bootstrap renderer for service accounts on the controller (#960).

Renders an IDEMPOTENT bash script that root runs ONCE to create a service
account (e.g. ``claudy``) on the controller box.  The script creates the unix
user, sets permissions, installs authorized_keys (fleet push keys + per-human
webterm forced-command keys), and enables loginctl linger — everything a
sudo-less controller box cannot do itself.

ZERO outbound imports by design (the L-E leaf convention); constants are
imported LAZILY inside render functions so the module loads with no side effects.
"""

import textwrap


# ---------------------------------------------------------------------------
# Service account registry — which accounts this renderer knows about
# ---------------------------------------------------------------------------

# Each entry defines the per-human tmux session names that webterm connects to.
# The keys of `webterm_sessions` are the humans whose webterm key gets a
# forced-command line in authorized_keys; the values are the tmux session
# `preferred` names those forced commands target.
SERVICE_ACCOUNTS = {
    "claudy": {
        "webterm_sessions": {
            "zbynek": "zbynek",     # owner's tmux session on claudy
            "marek": "marek",       # marek's tmux session on claudy
        },
    },
}


def _forced_command_key_line(preferred, pubkey):
    """Build a ``restrict,pty,command="..."`` authorized_keys line that
    attaches the named tmux session.  Mirrors ``_controller_lane_key_line``
    in ``cli_webterm_only.py`` — same forced-command shape, different
    ``preferred`` source (per SERVICE_ACCOUNTS, not per webterm-only user)."""
    from cli_webterm import _remote_command
    cmd = _remote_command(preferred)
    escaped_cmd = cmd.replace("\\", "\\\\").replace('"', '\\"')
    return 'restrict,pty,command="%s" %s' % (escaped_cmd, pubkey)


def desired_keys_for_service_account(account):
    """Return the list of authorized_keys lines for a service account.
    Raises ValueError for an unknown account."""
    if account not in SERVICE_ACCOUNTS:
        raise ValueError("unknown service account: %r" % account)

    from cli_webterm_only import FLEET_PUSH_PUBKEYS, WEBTERM_CONTROLLER_LANE_PUBKEYS
    from cli_owner_keys import OWNER_PUBKEYS

    keys = list(FLEET_PUSH_PUBKEYS)
    keys.extend(OWNER_PUBKEYS)

    # Per-human webterm forced-command keys
    spec = SERVICE_ACCOUNTS[account]
    for human in sorted(spec["webterm_sessions"]):
        preferred = spec["webterm_sessions"][human]
        pubkey = WEBTERM_CONTROLLER_LANE_PUBKEYS.get(human)
        if pubkey:
            keys.append(_forced_command_key_line(preferred, pubkey))

    return keys


def render_authorized_keys(account):
    """Render the full authorized_keys content for a service account."""
    header = (
        "# airuleset:managed — service account %s (#960); "
        "edits are overwritten by push\n" % account
    )
    lines = desired_keys_for_service_account(account)
    return header + "".join(line.rstrip("\n") + "\n" for line in lines)


def render_root_bootstrap(account):
    """Render an idempotent bash script for root that creates the service
    account on the controller.  Returns the script as a string."""
    if account not in SERVICE_ACCOUNTS:
        raise ValueError("unknown service account: %r" % account)

    ak_content = render_authorized_keys(account)
    # Shell-escape the authorized_keys content for a heredoc
    # Using a quoted heredoc delimiter so no shell expansion happens
    script = textwrap.dedent("""\
        #!/usr/bin/env bash
        set -euo pipefail

        # airuleset root bootstrap for service account '{account}' (#960)
        # Generated by: python3 airuleset.py account-bootstrap --render {account}
        # Run as root on the controller box. Idempotent.

        ACCOUNT='{account}'

        echo "=== airuleset root bootstrap: $ACCOUNT ==="

        # 1. Create user (idempotent)
        if id "$ACCOUNT" &>/dev/null; then
            echo "  user $ACCOUNT already exists — skipping useradd"
        else
            useradd -m -s /bin/bash -U "$ACCOUNT"
            echo "  created user $ACCOUNT"
        fi

        # 2. Home permissions
        chmod 0750 "/home/$ACCOUNT"
        echo "  home permissions: $(stat -c '%a' /home/$ACCOUNT)"

        # 3. Enable loginctl linger (reboot-durable user services)
        loginctl enable-linger "$ACCOUNT"
        echo "  linger: $(loginctl show-user "$ACCOUNT" -p Linger --value 2>/dev/null || echo 'enabled')"

        # 4. SSH directory
        install -d -m 0700 -o "$ACCOUNT" -g "$ACCOUNT" "/home/$ACCOUNT/.ssh"

        # 5. authorized_keys (atomic write)
        AK_TEMP=$(mktemp "/home/$ACCOUNT/.ssh/authorized_keys.XXXXXX")
        cat > "$AK_TEMP" << 'AUTHORIZED_KEYS_EOF'
        {ak_content}AUTHORIZED_KEYS_EOF
        chmod 0600 "$AK_TEMP"
        chown "$ACCOUNT":"$ACCOUNT" "$AK_TEMP"
        mv "$AK_TEMP" "/home/$ACCOUNT/.ssh/authorized_keys"
        echo "  authorized_keys: $(wc -l < /home/$ACCOUNT/.ssh/authorized_keys) lines"

        # 6. Create .claude directory for airuleset markers
        install -d -m 0755 -o "$ACCOUNT" -g "$ACCOUNT" "/home/$ACCOUNT/.claude"

        # 7. Create devel directory for the repo clone
        install -d -m 0755 -o "$ACCOUNT" -g "$ACCOUNT" "/home/$ACCOUNT/devel"

        echo ""
        echo "=== Read-back ==="
        echo "  user: $(id $ACCOUNT)"
        echo "  home: $(ls -ld /home/$ACCOUNT)"
        echo "  linger: $(loginctl show-user $ACCOUNT -p Linger --value 2>/dev/null || echo 'check manually')"
        echo "  ssh dir: $(ls -ld /home/$ACCOUNT/.ssh)"
        echo "  authorized_keys: $(wc -l < /home/$ACCOUNT/.ssh/authorized_keys) lines"
        echo "  key fingerprints:"
        ssh-keygen -lf "/home/$ACCOUNT/.ssh/authorized_keys" 2>/dev/null || echo "    (ssh-keygen failed)"
        echo ""
        echo "=== Next steps (as $ACCOUNT) ==="
        echo "  1. git clone https://github.com/zbynekdrlik/airuleset.git ~/devel/airuleset"
        echo "  2. python3 ~/devel/airuleset/airuleset.py install"
        echo "  3. Verify: ssh -i ~/.secrets/airuleset_push_ed25519 $ACCOUNT@100.101.214.103 true"
    """).format(account=account, ak_content=ak_content)
    return script


def cmd_account_bootstrap(args):
    """CLI entry point: ``airuleset.py account-bootstrap --render <account>``."""
    if len(args) < 2 or args[0] != "--render":
        print("Usage: airuleset.py account-bootstrap --render <account>",
              file=__import__("sys").stderr)
        print("Known accounts: %s" % ", ".join(sorted(SERVICE_ACCOUNTS)),
              file=__import__("sys").stderr)
        return 1
    account = args[1]
    try:
        script = render_root_bootstrap(account)
    except ValueError as e:
        print("ERROR: %s" % e, file=__import__("sys").stderr)
        return 1
    print(script)
    return 0
