# Universal profile — modules imported into ~/.claude/CLAUDE.md
# These apply to ALL projects via the global config.
# Size = tracked metric, never a target (mdreview: CONTENT is the indicator). Review due when resolved size grows >10% since last audit.
# Current (2026-05-30): Opus 4.8 literalism-optimized. Use /rules-audit to review periodically.

modules/core/machine-identities.md
modules/core/statusline-vocabulary.md
modules/core/model-awareness.md
modules/core/claude-code-tooling.md
modules/core/gh-cli-recipes.md
modules/core/response-structure.md
modules/core/message-status-marker.md
modules/core/issue-reference-context.md
modules/core/pr-merge-policy.md
modules/core/ci-monitoring.md
modules/core/tdd-workflow.md
modules/core/autonomous-verification.md
modules/core/complete-planned-work.md
modules/core/project-playbook-maintenance.md
modules/core/git-fetch-first.md
modules/core/version-bumping.md
modules/core/ci-push-discipline.md
modules/core/ask-before-assuming.md
modules/core/user-questions-slovak.md
modules/core/autonomous-quality-discipline.md
modules/core/milestone-notifications.md
modules/core/subagent-type-discipline.md
modules/core/subagent-continuation.md
modules/core/main-context-hygiene.md
modules/core/salvage-before-discarding-work.md
modules/core/view-image-urls.md
modules/core/deliver-files-as-urls.md
modules/core/receive-files-via-upload-url.md
modules/git/two-branch-workflow.md
modules/git/commit-conventions.md
modules/ci/test-strictness.md
rules/no-continue-on-error.md
rules/coverage-thresholds.md
rules/browser-console-zero-errors.md
rules/e2e-real-user-testing.md
modules/ci/mutation-testing.md
modules/deploy/mcp-error-handling.md
modules/deploy/post-deploy-verification.md
modules/deploy/deploy-from-clean-tree.md
modules/quality/architecture-first.md
modules/quality/investigate-existing-first.md
modules/quality/mvp-philosophy.md
modules/quality/security-basics.md
modules/quality/script-failure-policy.md
modules/quality/no-timeout-band-aids.md
modules/quality/no-local-builds.md
modules/quality/no-localhost-urls.md
modules/quality/no-destructive-remote-actions.md
modules/quality/approval-scope.md
rules/database-migrations.md
modules/quality/version-on-dashboard.md
modules/quality/comprehensive-logging.md
modules/quality/autonomous-batch-issue-development.md
modules/quality/regression-test-first.md
modules/quality/no-dropped-work.md
modules/quality/durable-decisions-to-tickets.md
modules/quality/verify-issue-still-valid.md
modules/quality/verify-launched-work-liveness.md
modules/core/completion-report.md
